# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chrphb-quarto-util',
                'doc_host': 'https://chrphb.github.io',
                'git_url': 'https://github.com/chrphb/chrphb-quarto-util',
                'lib_path': 'chrphb_quarto_util'},
  'syms': {'chrphb_quarto_util.core': {'chrphb_quarto_util.core.foo': ('core.html#foo', 'chrphb_quarto_util/core.py')}}}
