# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chrphb-quarto-util',
                'doc_host': 'https://chrphb.github.io',
                'git_url': 'https://github.com/chrphb/chrphb-quarto-util',
                'lib_path': 'chrphb_quarto_util'},
  'syms': { 'chrphb_quarto_util.core': { 'chrphb_quarto_util.core.create_post_from_template': ( 'core.html#create_post_from_template',
                                                                                                'chrphb_quarto_util/core.py'),
                                         'chrphb_quarto_util.core.generate_file_content': ( 'core.html#generate_file_content',
                                                                                            'chrphb_quarto_util/core.py')}}}
